jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: python update_market_data_pg.py
